"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Fingerprint, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";

const controls = ["JWT Authentication", "Role-Based Access", "Context-Aware Authorization", "Consent Verification", "Encrypted Clinical Data", "Tamper-Evident Audit"];

function AuthFrame({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
  return <main className="grid min-h-screen bg-background lg:grid-cols-[1.05fr_.95fr]">
    <section className="security-grid relative hidden overflow-hidden border-r p-12 lg:flex lg:flex-col lg:justify-between xl:p-16"><div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_20%,color-mix(in_srgb,var(--primary)_16%,transparent),transparent_32%)]"/><a href="/" className="relative z-10 flex w-fit items-center gap-3"><span className="grid size-10 place-items-center rounded-md border border-primary/40 bg-primary/10 text-primary"><ShieldCheck className="size-5"/></span><span><span className="block text-base font-bold tracking-[.18em]">SECUREHEALTH</span><span className="block text-[10px] font-semibold tracking-[.14em] text-muted-foreground">ZERO-TRUST EHR SECURITY</span></span></a><div className="relative z-10 my-14 max-w-xl"><p className="text-sm font-semibold uppercase tracking-[.15em] text-primary">Identity is the first control—not the last.</p><h1 className="mt-5 text-5xl font-semibold leading-[1.03] tracking-[-.045em]">Every clinical request earns access, one policy at a time.</h1><p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">SecureHealth verifies identity, role, context, patient consent, and resource scope before any protected record is released.</p><div className="mt-10 grid grid-cols-2 gap-2">{controls.map((item, index)=><div key={item} className="flex items-center gap-2 rounded-md border bg-card/45 px-3 py-2.5 text-xs font-medium"><span className="grid size-5 place-items-center rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-400"><Check className="size-3"/></span>{item}</div>)}</div></div><div className="relative z-10 flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-4 text-primary"/> Academic security prototype · HIPAA-aligned technical safeguards</div></section>
    <section className="flex min-h-screen items-center justify-center p-5 sm:p-10"><div className="w-full max-w-[440px]"><a href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to SecureHealth</a><div className="mb-8"><span className="mb-5 grid size-11 place-items-center rounded-lg border bg-card text-primary lg:hidden"><ShieldCheck className="size-5"/></span><h2 className="text-3xl font-semibold tracking-[-.035em]">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>{children}</div></section>
  </main>;
}

export function LoginPage() {
  const [role,setRole]=useState("admin"); const [loading,setLoading]=useState(false);
  function submit(e: React.FormEvent){e.preventDefault();setLoading(true);setTimeout(()=>{window.location.href=`/${role}/dashboard`},650)}
  return <AuthFrame title="Secure sign in" description="Continue to your protected SecureHealth workspace."><form onSubmit={submit} className="space-y-5"><div><label htmlFor="role" className="mb-2 block text-sm font-medium">Demo workspace</label><select id="role" value={role} onChange={(e)=>setRole(e.target.value)} className="h-11 w-full rounded-md border bg-card px-3 text-sm"><option value="admin">Security Administrator</option><option value="doctor">Doctor</option><option value="patient">Patient</option></select></div><div><label htmlFor="email" className="mb-2 block text-sm font-medium">Email</label><Input id="email" type="email" defaultValue="admin@securehealth.demo" required className="h-11"/></div><div><div className="mb-2 flex items-center justify-between"><label htmlFor="password" className="text-sm font-medium">Password</label><a href="/forgot-password" className="text-xs font-medium text-primary hover:underline">Forgot password?</a></div><Input id="password" type="password" defaultValue="secure-demo" required className="h-11"/></div><div className="flex items-center gap-2"><Checkbox id="remember" defaultChecked/><label htmlFor="remember" className="text-sm text-muted-foreground">Remember this session on this device</label></div><Button type="submit" className="h-11 w-full rounded-md" disabled={loading}>{loading ? "Verifying identity…" : <><Fingerprint className="size-4"/>Secure Login</>}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">New to the prototype? <a href="/register" className="font-medium text-primary hover:underline">Request access</a></p><div className="mt-8 border-t pt-5"><p className="text-center text-xs leading-5 text-muted-foreground">This is an academic security prototype. It demonstrates layered controls and does not claim HIPAA certification.</p></div></AuthFrame>;
}

export function RegisterPage() {
  const [sent,setSent]=useState(false);
  if(sent) return <AuthFrame title="Request received" description="Your workspace request is ready for administrator review."><div className="rounded-lg border border-emerald-500/25 bg-emerald-500/8 p-6 text-center"><span className="mx-auto grid size-11 place-items-center rounded-full border border-emerald-500/30 text-emerald-400"><Check className="size-5"/></span><h3 className="mt-4 font-semibold">Identity request submitted</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">A security administrator will validate your organization and requested role before access is provisioned.</p><Button asChild className="mt-5"><a href="/login">Return to sign in</a></Button></div></AuthFrame>;
  return <AuthFrame title="Request workspace access" description="Access is provisioned only after identity and organization validation."><form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="space-y-4"><div><label className="mb-2 block text-sm font-medium" htmlFor="name">Full name</label><Input id="name" required className="h-11"/></div><div><label className="mb-2 block text-sm font-medium" htmlFor="reg-email">Work email</label><Input id="reg-email" type="email" required className="h-11"/></div><div><label className="mb-2 block text-sm font-medium" htmlFor="organization">Organization</label><Input id="organization" required className="h-11"/></div><div><label className="mb-2 block text-sm font-medium" htmlFor="requested-role">Requested role</label><select id="requested-role" className="h-11 w-full rounded-md border bg-card px-3 text-sm"><option>Doctor</option><option>Security Administrator</option><option>Care Coordinator</option></select></div><Button type="submit" className="h-11 w-full">Submit for verification <ArrowRight className="size-4"/></Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already verified? <a href="/login" className="text-primary hover:underline">Sign in</a></p></AuthFrame>;
}

export function ForgotPasswordPage() {
  const [sent,setSent]=useState(false);
  return <AuthFrame title="Recover your account" description="We’ll send a time-limited recovery link after identity checks.">{sent?<div className="rounded-lg border border-blue-500/25 bg-blue-500/8 p-5"><div className="flex gap-3"><KeyRound className="size-5 text-blue-400"/><div><h3 className="text-sm font-semibold">Recovery link requested</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">If the account is valid, a secure recovery link has been sent. The request was added to the audit trail.</p></div></div><Button asChild variant="outline" className="mt-5 w-full"><a href="/login">Return to sign in</a></Button></div>:<form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="space-y-5"><div><label className="mb-2 block text-sm font-medium" htmlFor="recovery-email">Email</label><Input id="recovery-email" type="email" required className="h-11"/></div><Button className="h-11 w-full">Send secure recovery link</Button></form>}</AuthFrame>;
}
