"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, Ban, BookOpenCheck, Check, CheckCircle2, ChevronDown, ChevronRight, ClipboardCheck, Clock3, Database, Download, Eye, FileClock, FileKey2, FileText, Filter, HeartPulse, KeyRound, LockKeyhole, Network, Play, Plus, RefreshCcw, Search, ShieldAlert, ShieldCheck, Siren, SlidersHorizontal, Stethoscope, TriangleAlert, UserRoundCheck, Users, X, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "./app-shell";
import { Workspace } from "./dashboard-pages";
import { AuthorizationPipeline, ConsentChart, DecisionChart, DecisionDonut, EmptyState, HashChain, IntegritySequence, Panel, SecurityMetric, SecurityTimeline, StatusBadge } from "./security-ui";
import { mockAuditEvents, mockConsents, mockFHIRRequests, mockPatients, mockRecords, mockSecurityEvents, mockSentinelAlerts, mockUsers, serviceHealth } from "@/lib/mock-data";

const field = "h-10 w-full rounded-md border bg-background px-3 text-sm";

export function AccessRequestPage({ deniedDefault = false }: { deniedDefault?: boolean }) {
  const [scenario,setScenario]=useState(deniedDefault?"wrong-org":"authorized"); const [phase,setPhase]=useState<"form"|"running"|"result">("form"); const [recordOpen,setRecordOpen]=useState(false);
  const denied = scenario==="wrong-org"?["ABAC","CONSENT"]:scenario==="no-consent"?["CONSENT"]:scenario==="expired"?["CONSENT"]:scenario==="revoked"?["CONSENT"]:[];
  const isDenied=denied.length>0;
  useEffect(()=>{if(phase==="running"){const t=setTimeout(()=>setPhase("result"),2600);return()=>clearTimeout(t)}},[phase,scenario]);
  return <Workspace><PageHeader eyebrow="Authorization" title="Access request" subtitle="Protected records remain withheld until every policy control returns an explicit decision." status={<StatusBadge tone="info">Policy v4.12.8</StatusBadge>} actions={<Button asChild variant="outline" size="sm"><a href="/doctor/patients"><ArrowLeft className="size-4"/>Patient list</a></Button>}/>
    <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Panel title="Request context" description="Clinical and policy inputs sent to the authorization engine"><div className="space-y-4 p-5"><div><label className="mb-1.5 block text-xs font-medium" htmlFor="patient">Patient</label><select id="patient" className={field}><option>Avery Morgan · P001</option><option>Jordan Lee · P014</option><option>Theo Brooks · P038</option></select></div><div><label className="mb-1.5 block text-xs font-medium" htmlFor="resource">Resource</label><select id="resource" className={field}><option>Observation · Cardiology</option><option>DiagnosticReport · Laboratory</option><option>DocumentReference · Discharge</option></select></div><div><label className="mb-1.5 block text-xs font-medium" htmlFor="purpose">Purpose of use</label><select id="purpose" className={field}><option>Treatment / continuity of care</option><option>Diagnostic review</option><option>Care coordination</option></select></div><div><label className="mb-1.5 block text-xs font-medium" htmlFor="scenario">Security demo condition</label><select id="scenario" value={scenario} onChange={(e)=>{setScenario(e.target.value);setPhase("form")}} className={field}><option value="authorized">Authorized access</option><option value="wrong-org">Wrong organization</option><option value="no-consent">No consent</option><option value="expired">Expired consent</option><option value="revoked">Revoked consent</option></select></div><div className="grid grid-cols-2 gap-3 rounded-md border bg-muted/25 p-3 text-xs"><div><p className="text-muted-foreground">Requester</p><p className="mt-1 font-semibold">Dr. Maya Chen</p></div><div><p className="text-muted-foreground">Organization</p><p className="mt-1 font-semibold">{scenario==="wrong-org"?"Harbor Clinic":"Northstar Medical"}</p></div><div><p className="text-muted-foreground">Role</p><p className="mt-1 font-semibold">Cardiologist</p></div><div><p className="text-muted-foreground">Request ID</p><p className="mt-1 font-mono">REQ-7A91F2</p></div></div><Button className="h-11 w-full" onClick={()=>setPhase("running")} disabled={phase==="running"}><ShieldCheck className="size-4"/>{phase==="running"?"Evaluating policies…":"Evaluate access request"}</Button></div></Panel>
    <Panel title="Access request evaluation" description="Each layer evaluates independent policy evidence" action={<StatusBadge tone={phase==="running"?"info":phase==="result"?(isDenied?"critical":"success"):"neutral"} pulse={phase==="running"}>{phase==="running"?"Evaluating":phase==="result"?(isDenied?"Denied":"Granted"):"Ready"}</StatusBadge>}><div className="p-5"><AuthorizationPipeline denied={phase==="result"?denied:[]} running={phase==="running"}/>{phase==="result"&&!isDenied&&<div className="mt-5 rounded-md border border-emerald-500/25 bg-emerald-500/5 p-4"><div className="flex items-center gap-3"><CheckCircle2 className="size-5 text-emerald-400"/><div><p className="text-sm font-semibold">Policy evidence satisfied</p><p className="mt-1 text-xs text-muted-foreground">Minimum necessary clinical data is ready for release.</p></div></div><Button className="mt-4 w-full" onClick={()=>setRecordOpen(true)}><Eye className="size-4"/>View protected record</Button></div>}{phase==="result"&&isDenied&&<div role="alert" className="mt-5 rounded-md border border-red-500/30 bg-red-500/8 p-4"><div className="flex gap-3"><XCircle className="mt-0.5 size-5 text-red-400"/><div><p className="text-sm font-semibold">Authorization denied</p><ul className="mt-2 space-y-1 text-sm text-muted-foreground">{scenario==="wrong-org"&&<><li>• Organization mismatch</li><li>• No active consent for this organization and resource</li></>}{scenario==="no-consent"&&<li>• No active consent for this resource</li>}{scenario==="expired"&&<li>• Consent expired on Sep 22, 2026</li>}{scenario==="revoked"&&<li>• Consent was revoked; authorization cache invalidated</li>}</ul><p className="mt-3 font-mono text-[11px] text-muted-foreground">REQ-7A91F2 · 2026-09-27 14:42:18.921</p></div></div><div className="mt-4 flex gap-2"><Button asChild variant="outline" size="sm"><a href="/admin/security-events">View security details</a></Button><Button variant="ghost" size="sm" onClick={()=>setPhase("form")}>Return</Button></div></div>}</div></Panel></div>
    <Dialog open={recordOpen} onOpenChange={setRecordOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Protected clinical record</DialogTitle><DialogDescription>Released under request REQ-7A91F2 · purpose: continuity of care</DialogDescription></DialogHeader><div className="rounded-md border"><div className="flex items-center justify-between border-b p-4"><div><p className="text-sm font-semibold">Cardiology observation</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">FHIR Observation/OB-4471</p></div><StatusBadge tone="success">Authorized</StatusBadge></div><dl className="grid grid-cols-2 gap-px bg-border text-sm sm:grid-cols-3"><div className="bg-card p-4"><dt className="text-xs text-muted-foreground">Blood pressure</dt><dd className="mt-1 font-semibold">124/78 mmHg</dd></div><div className="bg-card p-4"><dt className="text-xs text-muted-foreground">Heart rate</dt><dd className="mt-1 font-semibold">68 bpm</dd></div><div className="bg-card p-4"><dt className="text-xs text-muted-foreground">Recorded</dt><dd className="mt-1 font-semibold">Sep 25, 09:18</dd></div></dl></div><DialogFooter><DialogClose asChild><Button>Close protected view</Button></DialogClose></DialogFooter></DialogContent></Dialog>
  </Workspace>;
}

export function ConsentCenterPage() {
  const [consents,setConsents]=useState(mockConsents); const [revoke,setRevoke]=useState<string|null>(null); const [granted,setGranted]=useState(false);
  function statusTone(s:string){return s==="Active"?"success":s==="Expiring"?"warning":s==="Revoked"?"critical":"neutral"}
  return <Workspace><PageHeader eyebrow="Privacy controls" title="Consent center" subtitle="Control which organizations may request specific health information, for a defined purpose and duration." actions={<Dialog><DialogTrigger asChild><Button size="sm"><Plus className="size-4"/>Grant consent</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Grant consent</DialogTitle><DialogDescription>Define the exact organization, resource, purpose, and duration.</DialogDescription></DialogHeader>{granted?<div className="rounded-md border border-emerald-500/25 bg-emerald-500/8 p-5 text-center"><CheckCircle2 className="mx-auto size-8 text-emerald-400"/><h3 className="mt-3 font-semibold">Consent granted</h3><p className="mt-1 text-sm text-muted-foreground">The persistent consent state and authorization policy cache are updated.</p></div>:<div className="space-y-4"><div><label className="mb-1.5 block text-xs font-medium">Organization</label><select className={field}><option>Northstar Medical</option><option>Harbor Diagnostics</option></select></div><div><label className="mb-1.5 block text-xs font-medium">Resource</label><select className={field}><option>Clinical records</option><option>Laboratory results</option><option>Imaging reports</option></select></div><div><label className="mb-1.5 block text-xs font-medium">Purpose</label><select className={field}><option>Continuity of care</option><option>Diagnostic review</option><option>Specialist consultation</option></select></div><div><label className="mb-1.5 block text-xs font-medium">Duration</label><select className={field}><option>30 days</option><option>90 days</option><option>1 year</option></select></div><div className="rounded-md border border-blue-500/25 bg-blue-500/7 p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-blue-400">You are granting</p><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">Organization</dt><dd className="mt-1 font-semibold">Northstar Medical</dd></div><div><dt className="text-muted-foreground">Resource</dt><dd className="mt-1 font-semibold">Clinical records</dd></div><div><dt className="text-muted-foreground">Purpose</dt><dd className="mt-1 font-semibold">Continuity of care</dd></div><div><dt className="text-muted-foreground">Duration</dt><dd className="mt-1 font-semibold">30 days</dd></div></dl></div></div>}<DialogFooter>{!granted&&<Button onClick={()=>{setGranted(true);setConsents([{id:"CON-NEW",org:"Northstar Medical",resource:"Clinical records",purpose:"Continuity of care",created:"Sep 27, 2026",expiry:"Oct 27, 2026",status:"Active"},...consents])}}>Confirm consent</Button>}<DialogClose asChild><Button variant="outline">{granted?"Done":"Cancel"}</Button></DialogClose></DialogFooter></DialogContent></Dialog>}/>
    <Tabs defaultValue="Active"><TabsList variant="line" className="mb-5 flex w-full justify-start overflow-x-auto border-b pb-1"><TabsTrigger value="Active">Active <span className="rounded bg-muted px-1.5 text-[10px]">{consents.filter(c=>c.status==="Active").length}</span></TabsTrigger><TabsTrigger value="Expiring">Expiring</TabsTrigger><TabsTrigger value="Expired">Expired</TabsTrigger><TabsTrigger value="Revoked">Revoked</TabsTrigger></TabsList>{["Active","Expiring","Expired","Revoked"].map(status=><TabsContent key={status} value={status}><div className="grid gap-4 lg:grid-cols-2">{consents.filter(c=>c.status===status).length?consents.filter(c=>c.status===status).map(c=><Panel key={c.id}><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-9 place-items-center rounded-md bg-primary/10 text-primary"><KeyRound className="size-4"/></span><div><h3 className="text-sm font-semibold">{c.org}</h3><p className="mt-1 font-mono text-[10px] text-muted-foreground">{c.id}</p></div></div><StatusBadge tone={statusTone(c.status)}>{c.status}</StatusBadge></div><dl className="mt-5 grid grid-cols-2 gap-4 border-t pt-4 text-xs"><div><dt className="text-muted-foreground">Resource</dt><dd className="mt-1 font-medium">{c.resource}</dd></div><div><dt className="text-muted-foreground">Purpose</dt><dd className="mt-1 font-medium">{c.purpose}</dd></div><div><dt className="text-muted-foreground">Created</dt><dd className="mt-1 font-medium">{c.created}</dd></div><div><dt className="text-muted-foreground">Expiry</dt><dd className="mt-1 font-medium">{c.expiry}</dd></div></dl><div className="mt-5 flex gap-2"><Button variant="outline" size="sm">View details</Button>{["Active","Expiring"].includes(c.status)&&<Button variant="ghost" size="sm" className="text-red-400" onClick={()=>setRevoke(c.id)}>Revoke</Button>}</div></div></Panel>):<div className="lg:col-span-2"><EmptyState title={`No ${status.toLowerCase()} consent`} description="Consent records in this state will appear here with their complete scope and audit history."/></div>}</div></TabsContent>)}</Tabs>
    <Dialog open={!!revoke} onOpenChange={(open)=>!open&&setRevoke(null)}><DialogContent><DialogHeader><DialogTitle>Revoke this consent?</DialogTitle><DialogDescription>Future access requests covered by this consent will be denied.</DialogDescription></DialogHeader><div className="space-y-2 rounded-md border border-red-500/25 bg-red-500/7 p-4 text-sm"><p className="flex items-center gap-2"><Check className="size-4 text-red-400"/>Persistent consent state updated</p><p className="flex items-center gap-2"><Check className="size-4 text-red-400"/>Authorization cache invalidated</p><p className="flex items-center gap-2"><Check className="size-4 text-red-400"/>Future requests denied</p><p className="flex items-center gap-2"><Check className="size-4 text-red-400"/>Audit event created</p></div><DialogFooter><Button variant="destructive" onClick={()=>{setConsents(consents.map(c=>c.id===revoke?{...c,status:"Revoked"}:c));setRevoke(null)}}>Revoke consent</Button><Button variant="outline" onClick={()=>setRevoke(null)}>Keep consent</Button></DialogFooter></DialogContent></Dialog>
  </Workspace>;
}

export function SecurityCenterPage() {
  return <Workspace><PageHeader eyebrow="Security operations" title="Security Center" subtitle="Enterprise authorization, integrity, and threat monitoring across the clinical data plane." status={<StatusBadge tone="success" pulse>System secure</StatusBadge>} actions={<Button asChild size="sm"><a href="/admin/security-events"><Activity className="size-4"/>Open live event stream</a></Button>}/><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><SecurityMetric label="Total requests" value="5,132" change="Last 24 hours" tone="info" icon={Activity}/><SecurityMetric label="Allowed" value="4,820" change="93.9%" tone="success" icon={ShieldCheck}/><SecurityMetric label="Denied" value="312" change="6.1%" tone="warning" icon={Ban}/><SecurityMetric label="Suspicious" value="14" change="3 open alerts" tone="critical" icon={Siren}/><SecurityMetric label="Critical" value="1" change="Requires investigation" tone="critical" icon={ShieldAlert}/></div>
  <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{serviceHealth.map(([name,status,detail])=><div key={name} className="rounded-lg border bg-card p-3.5"><div className="flex items-center justify-between"><span className="size-1.5 rounded-full bg-emerald-400"/><span className="font-mono text-[10px] text-muted-foreground">{detail}</span></div><p className="mt-3 text-xs font-semibold">{name}</p><p className="mt-1 text-[10px] font-medium text-emerald-400">{status}</p></div>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Panel title="Access decisions over time" description="Policy outcomes across authorization services"><DecisionChart/></Panel><Panel title="Allowed vs denied" description="Decision distribution, last 24 hours"><DecisionDonut/></Panel></div><div className="mt-5 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Panel title="Consent activity" description="Consent grants and revocations"><ConsentChart/></Panel><Panel title="Real-time security events" description="New verified events appear as they are committed"><SecurityTimeline/></Panel></div></Workspace>;
}

export function AuditPage({ detailId }: { detailId?: string }) {
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState<(typeof mockAuditEvents)[number]|null>(detailId?mockAuditEvents.find(e=>e.id===detailId)??mockAuditEvents[0]:null);
  const rows=mockAuditEvents.filter(e=>Object.values(e).join(" ").toLowerCase().includes(query.toLowerCase()));
  return <Workspace><PageHeader eyebrow="Trust controls" title="Audit history" subtitle="Searchable, evidence-rich authorization decisions with tamper-evident chain metadata." status={<StatusBadge tone="success">Chain valid</StatusBadge>} actions={<Button variant="outline" size="sm" onClick={()=>window.print()}><Download className="size-4"/>Export view</Button>}/><Panel><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search event, user, patient, resource…" className="pl-9"/></div><Button variant="outline" size="sm"><Filter className="size-4"/>Filters</Button><Button variant="outline" size="sm"><SlidersHorizontal className="size-4"/>Sort: newest</Button></div><Table><TableHeader><TableRow><TableHead>Timestamp</TableHead><TableHead>Event ID</TableHead><TableHead>User / Role</TableHead><TableHead>Organization</TableHead><TableHead>Patient</TableHead><TableHead>Resource</TableHead><TableHead>Action</TableHead><TableHead>Decision</TableHead><TableHead>Severity</TableHead></TableRow></TableHeader><TableBody>{rows.map(e=><TableRow key={e.id} className="cursor-pointer" onClick={()=>setSelected(e)}><TableCell className="font-mono text-[11px] text-muted-foreground">{e.time}</TableCell><TableCell className="font-mono text-[11px] text-primary">{e.id}</TableCell><TableCell><p className="font-medium">{e.user}</p><p className="text-xs text-muted-foreground">{e.role}</p></TableCell><TableCell>{e.org}</TableCell><TableCell className="font-mono text-xs">{e.patient}</TableCell><TableCell className="max-w-52 truncate font-mono text-xs">{e.resource}</TableCell><TableCell><StatusBadge tone="neutral">{e.action}</StatusBadge></TableCell><TableCell><StatusBadge tone={e.decision==="Allowed"?"success":"critical"}>{e.decision}</StatusBadge></TableCell><TableCell><StatusBadge tone={e.severity==="Info"?"info":e.severity==="Medium"?"warning":"critical"}>{e.severity}</StatusBadge></TableCell></TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-t px-4 py-3 text-xs text-muted-foreground"><span>Showing {rows.length} of 849,205 events</span><div className="flex gap-1"><Button variant="outline" size="sm" disabled>Previous</Button><Button variant="outline" size="sm">Next</Button></div></div></Panel>
  <Sheet open={!!selected} onOpenChange={(o)=>!o&&setSelected(null)}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-xl"><SheetHeader className="border-b p-5"><div className="flex items-center gap-2"><StatusBadge tone={selected?.decision==="Allowed"?"success":"critical"}>{selected?.decision??"Event"}</StatusBadge><StatusBadge tone="success">Chain verified</StatusBadge></div><SheetTitle className="pt-2 font-mono text-lg">{selected?.id}</SheetTitle><SheetDescription>{selected?.reason}</SheetDescription></SheetHeader>{selected&&<div className="p-5"><dl className="grid grid-cols-2 gap-4 text-xs">{[["Event ID",selected.id],["Request ID",selected.request],["Timestamp",selected.time],["User",selected.user],["Organization",selected.org],["Patient",selected.patient],["Resource",selected.resource],["Action",selected.action],["Purpose","Continuity of care"],["Decision",selected.decision],["IP",selected.ip],["User Agent","SecureHealth Client/4.8"]].map(([k,v])=><div key={k} className={k==="Resource"?"col-span-2":""}><dt className="text-muted-foreground">{k}</dt><dd className="mt-1 font-mono font-medium break-all">{v}</dd></div>)}</dl><div className="mt-6 rounded-md border bg-muted/20 p-4"><h3 className="text-xs font-bold uppercase tracking-[.1em]">Integrity evidence</h3><dl className="mt-4 space-y-3 text-xs"><div><dt className="text-muted-foreground">Previous Hash</dt><dd className="mt-1 break-all font-mono">8fe6c9a37e7a…b29021</dd></div><div><dt className="text-muted-foreground">Current Hash</dt><dd className="mt-1 break-all font-mono">a71d22bc90fe…4e8109</dd></div><div className="grid grid-cols-2 gap-4"><div><dt className="text-muted-foreground">Chain Position</dt><dd className="mt-1 font-mono">849,205</dd></div><div><dt className="text-muted-foreground">Checkpoint</dt><dd className="mt-1 font-mono">CP-00849</dd></div></div></dl><div className="mt-4 flex gap-2"><StatusBadge tone="success">Chain valid</StatusBadge><StatusBadge tone="success">Checkpoint verified</StatusBadge></div></div></div>}</SheetContent></Sheet></Workspace>;
}

export function IntegrityPage({ startTampered = false }: { startTampered?: boolean }) {
  const [tampered,setTampered]=useState(startTampered); const [verifying,setVerifying]=useState(false);
  function verify(){setVerifying(true);setTimeout(()=>setVerifying(false),1400)}
  return <Workspace><PageHeader eyebrow="Trust controls" title="Audit integrity" subtitle="Cryptographic chain representation and signed checkpoint verification for every recorded decision." status={<StatusBadge tone={tampered?"critical":"success"} pulse={tampered}>{tampered?"Integrity compromised":"Chain valid"}</StatusBadge>} actions={<><Button variant="outline" size="sm" onClick={()=>setTampered(!tampered)}>{tampered?"Restore demo chain":"Simulate tampering"}</Button><Button size="sm" onClick={verify} disabled={verifying}><RefreshCcw className={verifying?"size-4 animate-spin":"size-4"}/>{verifying?"Verifying…":"Verify integrity"}</Button></>}/>
  <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SecurityMetric label="Chain status" value={tampered?"INVALID":"VALID"} change={tampered?"Mismatch at event 849,203":"All links verified"} tone={tampered?"critical":"success"} icon={FileKey2}/><SecurityMetric label="Events verified" value={tampered?"849,202":"849,205"} change={tampered?"Verification stopped":"Through current position"} tone={tampered?"warning":"success"} icon={FileClock}/><SecurityMetric label="Last checkpoint" value="CP-00849" change="Sep 27 · 14:35:00" tone="info" icon={ShieldCheck}/><SecurityMetric label="Signature" value={tampered?"FAILED":"VERIFIED"} change={tampered?"Checkpoint rejected":"Ed25519 checkpoint"} tone={tampered?"critical":"success"} icon={KeyRound}/></div>
  {tampered&&<div role="alert" className="mb-5 rounded-lg border border-red-500/35 bg-red-500/10 p-5"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-md border border-red-500/35 text-red-400"><ShieldAlert className="size-5"/></span><div><p className="text-xs font-bold uppercase tracking-[.13em] text-red-400">Tampering detected</p><h2 className="mt-1 text-lg font-semibold">Audit event content no longer matches its recorded hash</h2><div className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><p className="text-muted-foreground">Expected Hash</p><p className="mt-1 font-mono">73c0b1e8a5…8d72</p></div><div><p className="text-muted-foreground">Actual Hash</p><p className="mt-1 font-mono text-red-400">91fe08a211…b4c9</p></div></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge tone="critical">Hash mismatch</StatusBadge><StatusBadge tone="critical">Chain invalid</StatusBadge><StatusBadge tone="critical">Checkpoint failed</StatusBadge></div></div></div></div>}
  <Panel title="Audit hash chain" description="Each event binds to the preceding event hash; later nodes become untrusted after a mismatch"><HashChain tampered={tampered}/></Panel><div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Verification flow" description={verifying?"Recomputing event digests and validating signed checkpoint evidence":"Latest verification outcome"}><IntegritySequence tampered={tampered}/></Panel><Panel title="Checkpoint evidence"><dl className="space-y-4 p-5 text-xs"><div className="flex justify-between"><dt className="text-muted-foreground">Chain position</dt><dd className="font-mono">849,205</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Checkpoint ID</dt><dd className="font-mono">CP-00849</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Created</dt><dd className="font-mono">14:35:00.000Z</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Verifier</dt><dd>audit-verifier-02</dd></div><div className="border-t pt-4"><StatusBadge tone={tampered?"critical":"success"}>{tampered?"Signature invalid":"Signature verified"}</StatusBadge></div></dl></Panel></div></Workspace>;
}
