"use client";
import { Activity, ArrowRight, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, FileKey2, FileText, HeartPulse, KeyRound, LockKeyhole, Network, ShieldCheck, Siren, Stethoscope, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { accessSeries, mockPatients, mockRecords, serviceHealth } from "@/lib/mock-data";
import { DecisionChart, Panel, SecurityMetric, SecurityTimeline, StatusBadge } from "./security-ui";
import { PageHeader } from "./app-shell";

function Workspace({ children }: { children: React.ReactNode }) { return <main className="mx-auto max-w-[1540px] p-4 sm:p-6 lg:p-8">{children}</main>; }

export function PatientDashboard() {
  return <Workspace><PageHeader eyebrow="Patient workspace" title="Good afternoon, Avery" subtitle="Your care overview and privacy controls are protected by active, purpose-bound consent." actions={<Button asChild size="sm"><a href="/patient/records"><FileText className="size-4"/>View records</a></Button>}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SecurityMetric label="Protected records" value="24" change="All encrypted at rest" tone="success" icon={FileKey2}/><SecurityMetric label="Active consents" value="3" change="1 expires in 5 days" tone="warning" icon={KeyRound}/><SecurityMetric label="Upcoming visits" value="2" change="Next: Sep 29, 09:30" tone="info" icon={CalendarDays}/><SecurityMetric label="Access events" value="12" change="No unusual activity" tone="success" icon={ShieldCheck}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Health overview" description="Current clinical summary from your protected record"><div className="grid gap-px bg-border sm:grid-cols-3"><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Latest reading</p><p className="mt-3 text-2xl font-semibold">124/78</p><p className="mt-1 text-xs text-emerald-400">Blood pressure · normal</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Active prescriptions</p><p className="mt-3 text-2xl font-semibold">3</p><p className="mt-1 text-xs text-muted-foreground">No refill action needed</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Care team</p><p className="mt-3 text-2xl font-semibold">4</p><p className="mt-1 text-xs text-muted-foreground">2 specialists · 2 primary</p></div></div><div className="border-t p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Cardiology consultation</p><p className="mt-1 text-xs text-muted-foreground">Sep 25 · Dr. Maya Chen · Northstar Medical</p></div><StatusBadge tone="success">Protected</StatusBadge></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Blood pressure is controlled. Continue the current care plan and return for follow-up in six weeks.</p></div></Panel>
    <Panel title="Recent access activity" description="Who accessed your information and why"><SecurityTimeline limit={4}/><div className="border-t p-3"><Button asChild variant="ghost" size="sm" className="w-full"><a href="/patient/security">Review all security activity <ArrowRight className="size-4"/></a></Button></div></Panel></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="Active consent" description="Organizations currently permitted to request your data"><div className="divide-y"><div className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-md bg-blue-500/10 text-blue-400"><Stethoscope className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Northstar Medical</p><p className="truncate text-xs text-muted-foreground">Clinical records · Continuity of care</p></div><StatusBadge tone="success">Active</StatusBadge></div><div className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-md bg-amber-500/10 text-amber-400"><Activity className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Harbor Diagnostics</p><p className="truncate text-xs text-muted-foreground">Laboratory results · Expires Oct 02</p></div><StatusBadge tone="warning">Expiring</StatusBadge></div></div><div className="border-t p-3"><Button asChild variant="outline" size="sm" className="w-full"><a href="/patient/consent">Manage consent</a></Button></div></Panel><Panel title="Upcoming care" description="Appointments and actions"><div className="divide-y"><div className="flex gap-4 p-4"><div className="w-12 text-center"><p className="text-[10px] font-bold uppercase text-primary">Sep</p><p className="text-xl font-semibold">29</p></div><div className="border-l pl-4"><p className="text-sm font-semibold">Cardiology follow-up</p><p className="mt-1 text-xs text-muted-foreground">09:30 · Dr. Maya Chen · Clinic 4B</p></div></div><div className="flex gap-4 p-4"><div className="w-12 text-center"><p className="text-[10px] font-bold uppercase text-primary">Oct</p><p className="text-xl font-semibold">06</p></div><div className="border-l pl-4"><p className="text-sm font-semibold">Routine laboratory panel</p><p className="mt-1 text-xs text-muted-foreground">08:00 · Harbor Diagnostics</p></div></div></div></Panel></div>
  </Workspace>;
}

export function DoctorDashboard() {
  return <Workspace><PageHeader eyebrow="Clinical workspace" title="Clinical workspace" subtitle="Today’s care activity, patient access context, and authorization queue." status={<StatusBadge tone="success">Consent-aware</StatusBadge>} actions={<Button asChild size="sm"><a href="/doctor/access-requests"><LockKeyhole className="size-4"/>New access request</a></Button>}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SecurityMetric label="Today's patients" value="8" change="3 seen · 5 remaining" tone="info" icon={UserRoundCheck}/><SecurityMetric label="Active consent" value="7/8" change="1 requires review" tone="warning" icon={KeyRound}/><SecurityMetric label="Access requests" value="3" change="2 approved · 1 pending" tone="info" icon={LockKeyhole}/><SecurityMetric label="Security events" value="1" change="No critical events" tone="success" icon={ShieldCheck}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Panel title="Today's patient schedule" description="Care relationship and consent are checked before record access"><div className="divide-y">{mockPatients.map((patient,index)=><div key={patient.id} className="flex flex-wrap items-center gap-3 px-4 py-3.5"><span className="grid size-9 place-items-center rounded-md bg-muted text-xs font-semibold">{patient.name.split(" ").map(n=>n[0]).join("")}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{patient.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{index===0?"09:30":index===1?"10:15":index===2?"13:00":"15:30"} · {patient.condition}</p></div><StatusBadge tone={patient.consent==="Active"?"success":patient.consent==="Expiring"?"warning":"critical"}>{patient.consent}</StatusBadge><Button asChild variant="outline" size="sm"><a href={`/doctor/patients/${patient.id}`}>Open workflow</a></Button></div>)}</div></Panel><Panel title="Access queue" description="Requests awaiting a security decision"><div className="divide-y"><div className="p-4"><div className="flex items-center justify-between"><StatusBadge tone="warning">Pending</StatusBadge><span className="font-mono text-[10px] text-muted-foreground">REQ-7B21C4</span></div><p className="mt-3 text-sm font-semibold">Jordan Lee · DiagnosticReport</p><p className="mt-1 text-xs text-muted-foreground">Purpose: treatment planning</p><Button asChild size="sm" className="mt-4 w-full"><a href="/doctor/access-requests">Evaluate request</a></Button></div><div className="p-4"><div className="flex items-center gap-2 text-xs text-emerald-400"><CheckCircle2 className="size-4"/> Approved 8 minutes ago</div><p className="mt-2 text-sm font-medium">Avery Morgan · Observation</p></div></div></Panel></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="Patient access workflow" description="Every request is evaluated through all active controls"><div className="p-5"><div className="flex items-center justify-between gap-2 overflow-x-auto">{["Request","Identity","RBAC","ABAC","Consent","Record","Audit"].map((step,i)=><div key={step} className="contents"><div className="min-w-16 text-center"><span className="mx-auto grid size-7 place-items-center rounded-full border border-emerald-500/30 bg-emerald-500/8 text-emerald-400"><CheckCircle2 className="size-3.5"/></span><p className="mt-2 text-[10px] font-semibold">{step}</p></div>{i<6&&<div className="h-px min-w-4 flex-1 bg-emerald-500/25"/>}</div>)}</div><p className="mt-5 border-t pt-4 text-xs leading-5 text-muted-foreground">Protected data is withheld until every policy layer returns an explicit decision.</p></div></Panel><Panel title="Upcoming appointments"><div className="divide-y"><div className="flex items-center gap-3 p-4"><Clock3 className="size-4 text-primary"/><div><p className="text-sm font-semibold">09:30 · Avery Morgan</p><p className="text-xs text-muted-foreground">Cardiology follow-up · Room 4B</p></div></div><div className="flex items-center gap-3 p-4"><Clock3 className="size-4 text-primary"/><div><p className="text-sm font-semibold">10:15 · Jordan Lee</p><p className="text-xs text-muted-foreground">Treatment plan review · Telehealth</p></div></div></div></Panel></div>
  </Workspace>;
}

export function AdminDashboard() {
  return <Workspace><PageHeader eyebrow="Security operations" title="Command center" subtitle="Authorization posture, integrity health, and real-time risk across the SecureHealth platform." status={<StatusBadge tone="success" pulse>System secure</StatusBadge>} actions={<><Button asChild variant="outline" size="sm"><a href="/demo">Run demo scenario</a></Button><Button asChild size="sm"><a href="/admin/security">Open Security Center <ArrowRight className="size-4"/></a></Button></>}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><SecurityMetric label="Requests / 24h" value="5,132" change="+8.4% from baseline" tone="info" icon={Activity}/><SecurityMetric label="Allowed" value="4,820" change="93.9% of requests" tone="success" icon={ShieldCheck}/><SecurityMetric label="Denied" value="312" change="6.1% policy denied" tone="warning" icon={LockKeyhole}/><SecurityMetric label="Suspicious" value="14" change="3 require review" tone="critical" icon={Siren}/><SecurityMetric label="Audit integrity" value="100%" change="849,205 events verified" tone="success" icon={FileKey2}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.42fr_.58fr]"><Panel title="Authorization decisions" description="Allowed and denied requests across the last 24 hours" action={<div className="flex items-center gap-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-blue-400"/>Allowed</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-red-400"/>Denied</span></div>}><DecisionChart/></Panel><Panel title="Live security events" description="Streaming from authorization, consent, and Sentinel"><SecurityTimeline limit={4}/><div className="border-t p-3"><Button asChild variant="ghost" size="sm" className="w-full"><a href="/admin/security-events">View live stream</a></Button></div></Panel></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Security services" description="Verified availability and response state"><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">{serviceHealth.map(([name,status,detail])=><a href="/admin/system-health" key={name} className="bg-card p-4 transition hover:bg-muted/35"><div className="flex items-center justify-between"><span className="grid size-8 place-items-center rounded-md bg-emerald-500/8 text-emerald-400"><HeartPulse className="size-4"/></span><span className="size-1.5 rounded-full bg-emerald-400"/></div><p className="mt-3 text-sm font-semibold">{name}</p><div className="mt-1 flex items-center justify-between text-xs"><span className="text-emerald-400">{status}</span><span className="font-mono text-muted-foreground">{detail}</span></div></a>)}</div></Panel><Panel title="Priority attention" description="Security work ordered by operational risk"><div className="divide-y"><a href="/admin/sentinel" className="flex items-center gap-3 p-4 hover:bg-muted/35"><span className="grid size-9 place-items-center rounded-md bg-red-500/10 text-red-400"><Siren className="size-4"/></span><div className="flex-1"><p className="text-sm font-semibold">Off-hours volume anomaly</p><p className="text-xs text-muted-foreground">Lena Ortiz · Harbor Clinic</p></div><StatusBadge tone="critical">Critical</StatusBadge></a><a href="/admin/emergency" className="flex items-center gap-3 p-4 hover:bg-muted/35"><span className="grid size-9 place-items-center rounded-md bg-amber-500/10 text-amber-400"><HeartPulse className="size-4"/></span><div className="flex-1"><p className="text-sm font-semibold">Break-glass review</p><p className="text-xs text-muted-foreground">1 expired session requires review</p></div><StatusBadge tone="warning">Review</StatusBadge></a><a href="/admin/fhir" className="flex items-center gap-3 p-4 hover:bg-muted/35"><span className="grid size-9 place-items-center rounded-md bg-blue-500/10 text-blue-400"><Network className="size-4"/></span><div className="flex-1"><p className="text-sm font-semibold">FHIR policy rejection</p><p className="text-xs text-muted-foreground">Cross-organization observation query</p></div><StatusBadge tone="info">Investigate</StatusBadge></a></div></Panel></div>
  </Workspace>;
}

export { Workspace };
